### ISSUE TITLE
Mongoose save ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by kevinnguyen20** [kevinnguyen20/Multi-client_Marketplace#1]

**Comment by gogokotsev00** [comment]
Ich bin wirklich enttäuscht, dass so ein Bug in unserem Projekt überhaupt existiert. ;)

**Comment by kevinnguyen20** [comment]
Fixed the bug in this commit e66603b33e8c538df3e17b7d67b3a73cb3b8d18e.
